### ISSUE TITLE
setvideo(true) not working

### ISSUE THREAD

**Issue by AmineNac** [jrvansuita/PickImage#70] opened 2018-04-20 12:56 UTC
After recording a video from the camera, the << pickResult.getPath() >> method returns this value 
 /*/MyCasa/20180420_134658.jpg. it's a JPG !!

**Comment by smail2133** [comment] 2018-05-23 09:48
The same issue, seems problem need solve by self!

**Comment by DmitriyYakovlev** [comment] 2018-08-01 13:27
Do you have any suggestions on when this will be fixed?

**Comment by DmitriyYakovlev** [comment] 2018-08-01 15:17
Note that, the problem is related to file extension only. There is workable video. I have tried to rename file manually and set .mp4 extension. File was fixed

**Comment by SD-LeadDeveloper** [comment] 2019-11-12 10:06
> Hey there, I think this pull request will solve the problems
> #97

Good Day, I am still experiencing this on 2.2.4 is there any way to fix it?

Kind Regards

**Comment by Joecorleone** [comment] 2020-03-29 14:51
I am also experiencing the same problem with 
    implementation 'com.github.jrvansuita:PickImage:2.2.4'
    implementation 'com.github.jrvansuita:PickImage:+'
Here is the merge, which should have fixed the problem:

 v2.1.0
Merge pull request #97 from molaeiali/master
Fix problems with video selection
on Oct 1, 2018 7a764d7 zip tar.gz 
>The resulting version is v2.1.0. (note the "v" added)

I tried to use exactly that version
    implementation 'com.github.jrvansuita:PickImage:v2.1.0'
but it does not contain neither the Module IPickCancel nor PickSetup().setVideo(true).

What is the solution?

**Closed** 2022-06-16 23:21 UTC
